apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
    {{- include "beacon-node.labels" . | nindent 4 }}
data:
  SERVER_NAME: {{ .Values.serverName | quote }}
  SERVER_REGION: {{ .Values.serverRegion | quote }}
  DB_HOST: {{ include "beacon-node.postgresql.host" . | quote }}
  DB_NAME: {{ include "beacon-node.postgresql.database" . | quote }}
  DB_USER: {{ include "beacon-node.postgresql.username" . | quote }}
  REDIS_HOST: {{ include "beacon-node.redis.host" . | quote }}
