apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
    {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.workers.enabled }}
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: worker-1
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: worker-2
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: worker-3
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: worker-4
    {{- end }}
  selector:
    {{- include "beacon-node.selectorLabels" . | nindent 4 }}
